### ISSUE TITLE
Error before 4B

### ISSUE THREAD

**Issue by kamaood** [SAND-Lab/MEA-NAP#56]
Hi,

I am experiencing this error before 4B.

Error using struct2table
Input structure is a scalar, but its fields have different numbers of rows. If you intended to create a
table with one row, set 'AsArray' to true.

**Comment by Timothysit** [comment]
Hi, can you check whether you have the latest version of the pipeline? You can check your version on the text section  when you launch the MEANAP GUI. We recently discovered that this error can occur when you have files with little or no activity, and I pushed the fix to this recently. 
![image](https://github.com/user-attachments/assets/91462dd2-9a17-4188-a889-3efce9d9f393)

**Comment by kamaood** [comment]
Yep I have the latest version of the pipeline and the error still occurs at 4B!

**Comment by Timothysit** [comment]
Hi, can you tell me which line of the code caused the error? Eg. if it's `PlotNetMet` at line 633 of the main script? And did you see any other warnings / errors in the matlab command window?

**Comment by Timothysit** [comment]
btw, you can re-run step 4B if you put step 4B in the start analysis step of the GUI

**Comment by kamaood** [comment]
Hi, yep I have been re-running and this is the error I get:

Error in saveNetMet (line 153)
allRecordingLevelDataTable = struct2table(allRecordingLevelData);

Error in MEApipeline (line 510)
        saveNetMet(ExpName, Params, HomeDir)

**Comment by Timothysit** [comment]
Okay, seems to be an issue in step 4, can you put a debug stop at line 153 of saveNetMet, then re-run (starting at step 4 if possible), and tell me what the variable `allRecordingLevelData` looks like?
